### ISSUE TITLE
N@TM Class Review

### ISSUE THREAD

**Issue by sarayu-pr11** [sarayu-pr11/Team-Colors#66]

**Comment by KrishnadevL** [comment]
Highlights: 
- Good idea for the API, incredibly useful towards new students 
- Good organization of links via navbar 
- ReadME is updated accurately  

Improvements: 
 - Could use a non-handwritten font for website to make it look a bit more modern

**Comment by JasonO12** [comment]
positives:
unique idea for project
very neatly laid out
nice readme

Improvement:
explain how code we learned helped on your site
